<?php


	namespace App\Contracts;


	interface DockerComposeRecipe{

	    public function label(): string;

        /**
         * Compute and builds the recipe
         * @return mixed
         */
	    public function build();

        /**
         * Setup the recipe
         * @return mixed
         */
        public function setup();

        /**
         * Get commands defined by the recipe
         * @return array
         */
        public function commands(): array;

        /**
         * Get hosts generated by the recipe
         * @return array
         */
        public function hosts(): array;

        /**
         * Get reachable addresses generated by the recipe
         * @return array
         */
        public function urls(): array;
	}
